# Generated by Django 3.1.7 on 2021-04-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present2web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_requried',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=True, verbose_name='Обязательный вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_answer',
            field=models.IntegerField(choices=[(0, 'Краткий ответ'), (1, 'Развернутый ответ'), (2, 'Один из списка'), (3, 'Несколько из списка'), (4, 'Дата')], verbose_name='Тип ответа'),
        ),
    ]
