# Generated by Django 3.1.7 on 2021-04-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present2web', '0002_auto_20210407_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_answer',
            field=models.IntegerField(choices=[(0, 'Краткий ответ'), (1, 'Развернутый ответ'), (2, 'Один из списка'), (3, 'Несколько из списка'), (4, 'Дата')], default=2, verbose_name='Тип ответа'),
        ),
    ]
