# Generated by Django 3.1.7 on 2021-05-25 18:04

from django.db import migrations, models
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('present2web', '0003_auto_20210407_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Уникальный id для анкеты')),
                ('presents_uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Уникальный id для анкеты')),
            ],
            options={
                'verbose_name': 'Временная ссылка',
                'verbose_name_plural': 'Временные ссылки',
            },
        ),
        migrations.AlterField(
            model_name='present',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='present',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=8),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='questions', to='present2web.Answer'),
        ),
    ]
