# Generated by Django 3.1.7 on 2021-05-28 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('present2web', '0004_auto_20210525_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempurl',
            name='category',
            field=models.IntegerField(default=1, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='presents_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Уникальный id для подарков'),
        ),
    ]
