# Generated by Django 3.1.7 on 2021-05-29 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('present2web', '0005_auto_20210528_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temp_urls', to='present2web.category', verbose_name='Категория'),
        ),
    ]
