# Generated by Django 3.1.7 on 2021-05-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present2web', '0008_auto_20210530_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='formulation',
            field=models.TextField(unique=True, verbose_name='Формулировка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.TextField(unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='present',
            name='name',
            field=models.TextField(unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='question',
            name='formulation',
            field=models.TextField(unique=True, verbose_name='Формулировка'),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='rules',
            field=models.TextField(blank=True, null=True, verbose_name='Правило вывода'),
        ),
    ]
